// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/theme-explorer/RedWhiteBlue.tsx": () => import("../components/mockups/theme-explorer/RedWhiteBlue.tsx"),
  "./components/mockups/theme-explorer/RedWhiteBlueAlt.tsx": () => import("../components/mockups/theme-explorer/RedWhiteBlueAlt.tsx")
};
